language: go
go:
- 1.2
- tip
install:
- go get github.com/stretchr/testify
- go build -v ./...
- go test -v ./...
env:
  global:
  - secure: Qteq+SIPntP5sQnQQC4dLHI5xCOkWHKNmvkbOMo3VuuKsFB2zUOTc0L8TAJU+tKMr81odIUxwyBKkafRix0JBWtnoGZ7RXGVVQ/KOp7U9i5B5meFOxIEvSPkFh9ykr2p/vvWAXs47OZfESzJbZeFlXMXXKUsBenu5jAYXwO4R+U=
  - secure: EDdTAcLzTaXhvIHpUM/BPOsISzPnJ44zR6twgRiMr3uihYvOyrTXq9tSPt8uJonma0/72T33zgLRJCPoUO9rbqWJvFcQlQWfcj/EYcD8Dwwhv+feKmYjvj7hM+ZMw2aEDqdHwYasn5b9LO21aBH0vp3loMZjJRY4p0QjkDEdJ0M=
  - FOURSQUARE_CLIENT_VERSION: 20130101
